// Generated from data/Ajustes.xlsx
export const RENAL_ADJUSTMENT_MEDICATIONS = [
  "Aciclovir",
  "Ácido Acetilsalicílico (AAS)",
  "Ácido Zoledrônico",
  "Alopurinol",
  "Amiodarona",
  "Amitriptilina",
  "Ampicilina",
  "Ampicilina + Sulbactam",
  "Atenolol",
  "Azacitidina",
  "Azatioprina",
  "Baclofeno",
  "Bleomicina",
  "Bromoprida",
  "Captopril",
  "Carboolatina",
  "Carboplatina",
  "Carfilzomibe",
  "Cefazolina",
  "Cefepima",
  "Ceftazidima",
  "Cetoprofeno",
  "Ciclofosfamida",
  "Cidofovir",
  "Cimetidina",
  "Ciprofloxacino",
  "Cisplatina",
  "Citarabina",
  "Cladribina",
  "Clonidina",
  "Codeína + Paracetamol",
  "Colchicina",
  "Dacarbazina",
  "Daptomicina",
  "Deslanosideo",
  "Dexmedetomidina",
  "Diazepam",
  "Diclofenaco",
  "Digoxina",
  "Diltiazem",
  "Enalapril",
  "Enoxaparina",
  "Esmolol",
  "Espironolactona",
  "Fenobarbital",
  "Fentanila",
  "Fluconazol",
  "Fludarabina",
  "Fluoruracila",
  "Foscarnet",
  "Fosfato de Potassio",
  "Furosemida",
  "Gabapentina",
  "Ganciclovir",
  "Gemcitabina",
  "Hidralazina",
  "Hidroclorotiazida",
  "Hidroxiureia",
  "Ibuprofeno",
  "Ifosfamida",
  "Irinotecano",
  "Lamivudina",
  "Levodopa + Carbidopa",
  "Levofloxacino",
  "Lorazepam",
  "Melfalano",
  "Mercaptopurina",
  "Meropenem",
  "Metoclopramida",
  "Metotrexato",
  "Micofenolato de Mofetila",
  "Micofenolato Mofetil",
  "Micofenolato Sodico",
  "Midazolam",
  "Morfina",
  "Nitrofurantoina",
  "Nitroprusseto",
  "Oxacilina",
  "Oxaliplatina",
  "Pamidronato",
  "Paracetamol",
  "Penicilina",
  "Piperacilina + Tazobactam",
  "Piridostigmina",
  "Rivaroxabana",
  "Sulfametoxazol + Trimetoprima",
  "Sulfato de Magnesio",
  "Tacrolimo",
  "Tenofovir + Lamivudina",
  "Tobramicina",
  "Topotecana",
  "Topotecano",
  "Tramadol",
  "Trioxido de Arsenio",
  "Vancomicina",
  "Vimblastina",
  "Vinorelbina",
  "Voriconazol",
  "Zidovudina",
  "PIPERACILINA+TAZOBACTAM",
  "Amoxicilina",
] as const;

export const HEPATOTOXIC_MEDICATIONS = [
  "Ácido 4-aminosalicílico",
  "Abacavir",
  "ACARBOSE",
  "Paracetamol",
  "Acetazolamida",
  "acitretina",
  "alaproclato",
  "Mesilato de alatofloxacina",
  "Albendazol",
  "Alclofenaco",
  "alopurinol",
  "alpidem",
  "amineptina",
  "amiodarona",
  "asparaginase",
  "atomoxetina",
  "atorvastatina",
  "azatioprina",
  "Benzarone",
  "Benzbromarone",
  "Benziodarona",
  "Bexarotene",
  "bicalutamida",
  "Bortezomibe",
  "Bosentana",
  "Bromfenac",
  "Bussulfano",
  "carbamazepina",
  "Ciprofloxacino",
  "claritromicina",
  "Clomacran",
  "Clomipramina",
  "Clozapina",
  "ciclosporina",
  "citarabina",
  "Dacarbazina",
  "Dactinomicina",
  "Danazol",
  "Dantroleno",
  "darunavir",
  "Deferasirox",
  "diclofenaco",
  "didanosina",
  "diflunisal",
  "Diltiazem",
  "DISULFIRAM",
  "Dronenarone",
  "Droxicam",
  "Duloxetina",
  "Ebrotidina",
  "Efavirenz",
  "erlotinibe",
  "eritromicina",
  "Estramustina",
  "Etambutol",
  "Etodolaco",
  "ETRAVIRINE",
  "Exemestano",
  "exifone",
  "falnidamol",
  "febuxostat",
  "Felbamate",
  "ácido fonclozico",
  "fenoprofeno",
  "Fialuridina",
  "Fiduxosina",
  "fipexido",
  "fluconazol",
  "flutamida",
  "Fosfenitoína",
  "gefitinibe",
  "gemcitabina",
  "Gemfibrozil",
  "Ozogamicina Gemtuzumab",
  "Glafenina",
  "hidroxiureia",
  "Imatinibe",
  "Indometacina",
  "infliximab",
  "interferon alfa-2a",
  "interferon alfa-2b",
  "interferon alfacon-1",
  "interferon beta-1a",
  "interferon beta-1b",
  "isaxonina",
  "Isoniazina",
  "isotretinoína",
  "itraconazol",
  "cetoconazol",
  "lamotrigina",
  "Lapatinib",
  "Leflunomida",
  "Levofloxacino",
  "mebanazine",
  "ácido mefenâmico",
  "mepazina",
  "Mercaptopurina",
  "Metimazol",
  "metotrexato",
  "Metildopa",
  "mexiletina",
  "Micafungina",
  "nitrefazol",
  "nitrofurantoína",
  "Nomifensina",
  "Nortriptilina",
  "oxaliplatina",
  "Oxandrolona",
  "Oximetolona",
  "oxifenisatina",
  "Pafuraidine",
  "Papaverine",
  "Pazopanib",
  "pegutorferon alfa-2b",
  "pemolina",
  "pentostatina",
  "perhexilina",
  "fenoxipropazina",
  "fenitoína",
  "Pipamazina",
  "pirprofeno",
  "propiltiouracil",
  "Raltegravir",
  "Rifampina",
  "Riluzol",
  "Ritonavir",
  "SitaxSentan",
  "sorafenib",
  "Stavudine",
  "sulcotidil",
  "sulfacarbamida",
  "sulfasalazina",
  "sulfatiazol",
  "Sulindac",
  "Sunitinibe",
  "tamoxifeno",
  "Tasosartan",
  "telitromicina",
  "Terbinafine",
  "testosterona",
  "tetrabamato",
  "Tiabendazol",
  "Ticlopidina",
  "tilbroquinol",
  "Tipranavir",
  "Tizanidina",
  "Tolcapone",
  "Tolrestat",
  "Tolvaptan",
  "troglitazona",
  "trovafloxacina",
  "ácido valpróico",
  "voriconazol",
  "ácido xenazóico",
  "Ximelagatran",
  "Zafirlukast",
  "Zidovudina",
  "Zileuton",
  "Zimelidina",
] as const;
